### ISSUE TITLE
Constantly throws TypeInitializationException when using VS2022

### ISSUE THREAD

**Issue by GuildOfCalamity** [Dreamescaper/IntelliSenseExtender#74]
System.TypeInitializationException : The type initializer for 'IntelliSenseExtender.ExposedInternals.SymbolCompletionItem' threw an exception. ---> System.NullReferenceException : Object reference not set to an instance of an object.
   at IntelliSenseExtender.ExposedInternals.SymbolCompletionItem..cctor()
   --- End of inner exception stack trace ---
   at IntelliSenseExtender.ExposedInternals.SymbolCompletionItem.EncodeSymbol(ISymbol symbol)
   at async IntelliSenseExtender.IntelliSense.CompletionItemHelper.GetDescriptionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async IntelliSenseExtender.IntelliSense.Providers.AggregateTypeCompletionProvider.GetDescriptionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by GuildOfCalamity** [comment]
I guessing this project is dead? Last commit was 2 years ago?

**Comment by Dreamescaper** [comment]
It's certainly not in active development, as a lot of things are already included in VS itself.

That said, I'll try to update it to work with the latest VS.

**Comment by Dreamescaper** [comment]
I have published an updated version, it should work fine with the latest version.
https://marketplace.visualstudio.com/items?itemName=Dreamescaper.IntelliSenseExtender2022

**Comment by GuildOfCalamity** [comment]
@Dreamescaper Thank you!
